// WARNING!! DANGER!! THIS FILE IS AUTOMATIGICALLY GENERATED BY "gulp"
// THE SOURCE FILE IS infl-icons/templates/influicons-list.js

var icons = {

<%

_.each(glyphs, function(glyph) {
  if (glyph.name != '500donotdeletethis') {
  %>
    "<%= glyph.name %>": "<%= glyph.name %>",
  <%
  }
});

%>

};

exports.icons = icons;