// WARNING!! DANGER!! THIS FILE IS AUTOMATIGICALLY GENERATED BY "gulp"
// THE SOURCE FILE IS infl-icons/templates/influicons-list.js

var icons = {


    "alert-caution": "alert-caution",
  
    "arrow-down": "arrow-down",
  
    "arrow-left": "arrow-left",
  
    "arrow-right": "arrow-right",
  
    "arrow-up": "arrow-up",
  
    "asterisk": "asterisk",
  
    "bell": "bell",
  
    "calendar": "calendar",
  
    "check-circle-o": "check-circle-o",
  
    "check": "check",
  
    "chevron-down": "chevron-down",
  
    "chevron-left": "chevron-left",
  
    "chevron-right": "chevron-right",
  
    "chevron-up": "chevron-up",
  
    "clock": "clock",
  
    "close-circle-o": "close-circle-o",
  
    "close": "close",
  
    "code": "code",
  
    "coins": "coins",
  
    "copy": "copy",
  
    "email-share": "email-share",
  
    "empty": "empty",
  
    "exclamation-circle-o": "exclamation-circle-o",
  
    "fb-filled": "fb-filled",
  
    "fb": "fb",
  
    "flag": "flag",
  
    "gear": "gear",
  
    "globe": "globe",
  
    "grid": "grid",
  
    "hamburger": "hamburger",
  
    "heart": "heart",
  
    "info-circle-o": "info-circle-o",
  
    "linkedin-filled": "linkedin-filled",
  
    "linkedin": "linkedin",
  
    "list": "list",
  
    "lock": "lock",
  
    "mail": "mail",
  
    "merge": "merge",
  
    "minus": "minus",
  
    "pencil": "pencil",
  
    "pin": "pin",
  
    "plus": "plus",
  
    "question-circle-o": "question-circle-o",
  
    "quote-close": "quote-close",
  
    "quote-fill-close": "quote-fill-close",
  
    "quote-fill-open": "quote-fill-open",
  
    "quote-open": "quote-open",
  
    "search": "search",
  
    "share": "share",
  
    "speech-2": "speech-2",
  
    "speech": "speech",
  
    "star": "star",
  
    "support": "support",
  
    "target": "target",
  
    "times-circle-o": "times-circle-o",
  
    "times": "times",
  
    "trash": "trash",
  
    "twitter-filled": "twitter-filled",
  
    "twitter": "twitter",
  
    "unlock": "unlock",
  
    "user": "user",
  

};

exports.icons = icons;